icons/evolvere-black-folders usr/share/icons
icons/evolvere-black-folders-dark usr/share/icons
icons/evolvere-black-folders-dark-fallback usr/share/icons
icons/evolvere-black-folders-dark-light-fallback usr/share/icons
icons/evolvere-black-folders-vivid usr/share/icons
icons/evolvere-black-folders-vivid-dark usr/share/icons
icons/evolvere-black-folders-vivid-dark-fallback usr/share/icons
icons/evolvere-black-folders-vivid-dark-light-fallback usr/share/icons
